project_id = "calyxai"

[functions.gemini-chat]
verify_jwt = true

[functions.save-gemini-key]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
